import { Project, Task, Alert } from '@/types/project';
import { Message, Announcement, Approval } from '@/types/inbox';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Riverside Tower',
    address: '450 River Rd',
    city: 'Austin',
    state: 'TX',
    description: '32-story mixed-use residential tower with ground-floor retail',
    value: '$48,000,000',
    startDate: '2025-09-15',
    completionDate: '2027-03-01',
    status: 'active',
    stage: 'Foundation',
    sector: 'Residential',
    squareFootage: '285,000',
    trades: ['Concrete', 'Steel', 'Electrical', 'Plumbing'],
    imageUrl: null,
    lastActivity: '2 hours ago',
    progress: 0.18,
  },
  {
    id: '2',
    name: 'Metro Health Campus',
    address: '1200 Medical Dr',
    city: 'Dallas',
    state: 'TX',
    description: 'Medical office building and outpatient surgery center',
    value: '$22,500,000',
    startDate: '2025-11-01',
    completionDate: '2027-01-15',
    status: 'active',
    stage: 'Structural Steel',
    sector: 'Healthcare',
    squareFootage: '145,000',
    trades: ['Steel', 'HVAC', 'Fire Protection', 'Drywall'],
    imageUrl: null,
    lastActivity: '30 min ago',
    progress: 0.35,
  },
  {
    id: '3',
    name: 'Greenfield Distribution',
    address: '8900 Logistics Pkwy',
    city: 'Houston',
    state: 'TX',
    description: 'Large-format warehouse and distribution center with cold storage',
    value: '$15,800,000',
    startDate: '2026-01-10',
    completionDate: '2026-11-30',
    status: 'active',
    stage: 'Site Work',
    sector: 'Industrial',
    squareFootage: '320,000',
    trades: ['Excavation', 'Concrete', 'Metal Building', 'Refrigeration'],
    imageUrl: null,
    lastActivity: '1 day ago',
    progress: 0.08,
  },
  {
    id: '4',
    name: 'Summit Office Park',
    address: '300 Summit Blvd',
    city: 'San Antonio',
    state: 'TX',
    description: 'Class A office campus — two 6-story buildings with parking structure',
    value: '$36,000,000',
    startDate: '2025-06-01',
    completionDate: '2027-06-01',
    status: 'active',
    stage: 'Interior Finishes',
    sector: 'Commercial',
    squareFootage: '210,000',
    trades: ['Drywall', 'Flooring', 'Painting', 'Elevator'],
    imageUrl: null,
    lastActivity: '5 hours ago',
    progress: 0.62,
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    projectName: 'Riverside Tower',
    title: 'Submit rebar inspection report',
    description: 'Level 3 rebar placement needs sign-off before pour',
    assignee: 'Mike Torres',
    dueDate: '2026-03-28',
    status: 'overdue',
    priority: 'urgent',
  },
  {
    id: '2',
    projectId: '2',
    projectName: 'Metro Health Campus',
    title: 'Review MEP coordination drawings',
    description: 'Clash detection review meeting with subs',
    assignee: 'Sarah Chen',
    dueDate: '2026-03-29',
    status: 'in_progress',
    priority: 'high',
  },
  {
    id: '3',
    projectId: '1',
    projectName: 'Riverside Tower',
    title: 'Schedule crane inspection',
    description: 'Monthly tower crane safety certification',
    assignee: 'James Wilson',
    dueDate: '2026-04-01',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '4',
    projectId: '4',
    projectName: 'Summit Office Park',
    title: 'Approve flooring samples',
    description: 'Client walkthrough for Bldg A lobby finishes',
    assignee: 'You',
    dueDate: '2026-03-30',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '5',
    projectId: '3',
    projectName: 'Greenfield Distribution',
    title: 'Update grading plan',
    description: 'Revised stormwater management per civil engineer feedback',
    assignee: 'David Park',
    dueDate: '2026-04-02',
    status: 'todo',
    priority: 'low',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    type: 'delivery',
    title: 'Steel delivery arriving',
    description: '14 tons structural steel — Bay 3 staging area',
    projectName: 'Riverside Tower',
    time: 'Tomorrow, 7:00 AM',
    urgent: false,
  },
  {
    id: '2',
    type: 'rental',
    title: 'Scissor lift rental expiring',
    description: 'JLG 3394RT — return or extend by Friday',
    projectName: 'Summit Office Park',
    time: 'Mar 29',
    urgent: true,
  },
  {
    id: '3',
    type: 'weather',
    title: 'Storm warning',
    description: 'High winds expected 40+ mph — secure loose materials',
    projectName: 'All Projects',
    time: 'Thursday PM',
    urgent: true,
  },
  {
    id: '4',
    type: 'inspection',
    title: 'Fire marshal inspection',
    description: 'Scheduled walk-through — ensure all egress paths clear',
    projectName: 'Metro Health Campus',
    time: 'Apr 1, 10:00 AM',
    urgent: false,
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    senderName: 'Sarah Chen',
    senderAvatar: null,
    projectName: 'Metro Health Campus',
    preview: 'The MEP drawings look good but I found 3 clashes in the surgical suite area...',
    timestamp: '10:32 AM',
    unread: true,
  },
  {
    id: '2',
    senderName: 'Mike Torres',
    senderAvatar: null,
    projectName: 'Riverside Tower',
    preview: 'Rebar inspection passed. We are clear to pour Level 3 on Monday.',
    timestamp: '9:15 AM',
    unread: true,
  },
  {
    id: '3',
    senderName: 'Lisa Park',
    senderAvatar: null,
    projectName: 'Summit Office Park',
    preview: 'Client wants to see the marble samples before we proceed. Can you set up a meeting?',
    timestamp: 'Yesterday',
    unread: false,
  },
  {
    id: '4',
    senderName: 'James Wilson',
    senderAvatar: null,
    projectName: 'Greenfield Distribution',
    preview: 'Excavation crew hitting rock at 8ft. Need to discuss blasting vs. hydraulic breaking.',
    timestamp: 'Yesterday',
    unread: false,
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Safety Stand-Down Week',
    body: 'All sites will participate in OSHA Safety Stand-Down April 7-11. Schedule TBH training sessions for all crews.',
    author: 'Corporate Safety',
    timestamp: 'Mar 26',
    priority: 'important',
  },
  {
    id: '2',
    title: 'New Timecard System',
    body: 'Starting April 1, all field hours must be logged through the Construxa app. Paper timecards will no longer be accepted.',
    author: 'Operations',
    timestamp: 'Mar 24',
    priority: 'normal',
  },
];

export const mockApprovals: Approval[] = [
  {
    id: '1',
    documentName: 'Foundation Plan Rev. C',
    type: 'drawing',
    requester: 'Structural Engineering Co.',
    projectName: 'Riverside Tower',
    date: 'Mar 25',
    status: 'pending',
    flowSteps: [
      { role: 'Subcontractor', status: 'approved' },
      { role: 'GC', status: 'pending' },
      { role: 'Owner', status: 'waiting' },
    ],
    currentStep: 1,
  },
  {
    id: '2',
    documentName: 'HVAC Submittal #12',
    type: 'submittal',
    requester: 'AirFlow Mechanical',
    projectName: 'Metro Health Campus',
    date: 'Mar 24',
    status: 'pending',
    flowSteps: [
      { role: 'Subcontractor', status: 'approved' },
      { role: 'GC', status: 'approved' },
      { role: 'Owner', status: 'pending' },
    ],
    currentStep: 2,
  },
  {
    id: '3',
    documentName: 'Progress Invoice #7',
    type: 'invoice',
    requester: 'Elite Concrete LLC',
    projectName: 'Greenfield Distribution',
    date: 'Mar 23',
    status: 'approved',
    flowSteps: [
      { role: 'Subcontractor', status: 'approved' },
      { role: 'GC', status: 'approved' },
      { role: 'Owner', status: 'approved' },
    ],
    currentStep: 2,
  },
];

export const workflowFeatures = [
  { id: 'speech', label: 'Speech to Text', description: 'Voice logging & reporting', icon: 'mic' as const },
  { id: 'photos', label: 'Capture Photos', description: 'Organize site photos', icon: 'camera' as const },
  { id: 'documents', label: 'Manage Documents', description: 'Upload & organize files', icon: 'document' as const },
  { id: 'tasks', label: 'Manage Tasks', description: 'Track & assign work', icon: 'task' as const },
  { id: 'inspection', label: 'Inspections', description: 'Code compliance assistant', icon: 'shield' as const },
  { id: 'dispute', label: 'Dispute Assistant', description: 'Resolve conflicts', icon: 'alert' as const },
  { id: 'rfi', label: 'RFI Generator', description: 'Auto-generate RFIs', icon: 'document' as const },
  { id: 'permit', label: 'Permit Helper', description: 'Streamline permits', icon: 'checkCircle' as const },
];

export const pricingPlans = [
  {
    id: 'free',
    name: 'Free',
    price: '$0',
    period: 'forever',
    features: ['1 Project', '3 Users', 'Limited AI Features', '2 GB Storage'],
    highlighted: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    price: '$50',
    period: '/user/month',
    features: ['20 Projects', 'Full AI Features', 'Basic Integrations', 'Real Time Sync', '50 GB/user'],
    highlighted: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: '$100',
    period: '/user/month',
    features: ['Unlimited Projects', 'Role Management', 'Approval Flows', 'Document Flows', 'Analytics & API', '500 GB/user'],
    highlighted: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    features: ['Unlimited Users', 'Advanced Integrations', 'Custom Workflows', 'Dedicated Support', 'SLA + Compliance', '1 TB/user'],
    highlighted: false,
  },
];

export const countries = [
  'United States', 'Canada', 'Mexico', 'United Kingdom', 'Australia',
  'Germany', 'France', 'Brazil', 'Japan', 'India', 'Other',
];

export const roles = [
  'General Contractor', 'Subcontractor', 'Project Manager', 'Superintendent',
  'Foreman', 'Estimator', 'Architect', 'Engineer', 'Inspector', 'Owner/Developer',
];

export const trades = [
  'General', 'Electrical', 'Plumbing', 'HVAC', 'Concrete', 'Steel',
  'Carpentry', 'Drywall', 'Painting', 'Roofing', 'Excavation', 'Fire Protection',
  'Flooring', 'Masonry', 'Glazing', 'Landscaping', 'Other',
];

export const mockDeliveries = [
  { id: '1', item: 'Structural Steel — 14 tons', supplier: 'Atlas Steel Co.', date: 'Mar 28', status: 'scheduled' as const },
  { id: '2', item: 'Ready-mix Concrete (40 yd\u00B3)', supplier: 'Metro Concrete', date: 'Mar 29', status: 'scheduled' as const },
  { id: '3', item: 'Electrical Conduit & Wire', supplier: 'Sparks Supply', date: 'Apr 1', status: 'pending' as const },
];
